class ErrorCode:
    NODO_NO_ENCONTRADO = "El nodo no fue encontrado."

# Lista de tipos de datos iniciales
TIPOS_DE_DATOS_INICIALES = [
    {"nombre": "TEMP_T", "unidad": "°C", "rango_minimo": -50, "rango_maximo": 50, "umbral_alerta_precaucion": 40, "umbral_alerta_peligro": 45},
    {"nombre": "TEMP2_T", "unidad": "°C", "rango_minimo": -50, "rango_maximo": 50, "umbral_alerta_precaucion": 40, "umbral_alerta_peligro": 45},
    {"nombre": "HUMIDITY_T", "unidad": "%", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 80, "umbral_alerta_peligro": 90},
    {"nombre": "PRESSURE_T", "unidad": "hPa", "rango_minimo": 300, "rango_maximo": 1100, "umbral_alerta_precaucion": 1050, "umbral_alerta_peligro": 1100},
    {"nombre": "LIGHT_T", "unidad": "lux", "rango_minimo": 0, "rango_maximo": 100000, "umbral_alerta_precaucion": 80000, "umbral_alerta_peligro": 90000},
    {"nombre": "SOIL_T", "unidad": "%", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 90, "umbral_alerta_peligro": 95},
    {"nombre": "SOIL2_T", "unidad": "%", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 90, "umbral_alerta_peligro": 95},
    {"nombre": "SOILR_T", "unidad": "ohm", "rango_minimo": 0, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9500},
    {"nombre": "SOILR2_T", "unidad": "ohm", "rango_minimo": 0, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9500},
    {"nombre": "OXYGEN_T", "unidad": "%", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 80, "umbral_alerta_peligro": 85},
    {"nombre": "CO2_T", "unidad": "ppm", "rango_minimo": 0, "rango_maximo": 5000, "umbral_alerta_precaucion": 2000, "umbral_alerta_peligro": 4500},
    {"nombre": "WINDSPD_T", "unidad": "m/s", "rango_minimo": 0, "rango_maximo": 60, "umbral_alerta_precaucion": 40, "umbral_alerta_peligro": 50},
    {"nombre": "WINDHDG_T", "unidad": "°", "rango_minimo": 0, "rango_maximo": 360, "umbral_alerta_precaucion": None, "umbral_alerta_peligro": None},
    {"nombre": "RAINFALL_T", "unidad": "mm", "rango_minimo": 0, "rango_maximo": 500, "umbral_alerta_precaucion": 300, "umbral_alerta_peligro": 400},
    {"nombre": "MOTION_T", "unidad": "boolean", "rango_minimo": 0, "rango_maximo": 1, "umbral_alerta_precaucion": None, "umbral_alerta_peligro": None},
    {"nombre": "VOLTAGE_T", "unidad": "V", "rango_minimo": 0, "rango_maximo": 240, "umbral_alerta_precaucion": 220, "umbral_alerta_peligro": 230},
    {"nombre": "VOLTAGE2_T", "unidad": "V", "rango_minimo": 0, "rango_maximo": 240, "umbral_alerta_precaucion": 220, "umbral_alerta_peligro": 230},
    {"nombre": "CURRENT_T", "unidad": "A", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 80, "umbral_alerta_peligro": 90},
    {"nombre": "CURRENT2_T", "unidad": "A", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 80, "umbral_alerta_peligro": 90},
    {"nombre": "IT_T", "unidad": "int", "rango_minimo": 0, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9500},
    {"nombre": "LATITUDE_T", "unidad": "°", "rango_minimo": -90, "rango_maximo": 90, "umbral_alerta_precaucion": None, "umbral_alerta_peligro": None},
    {"nombre": "LONGITUDE_T", "unidad": "°", "rango_minimo": -180, "rango_maximo": 180, "umbral_alerta_precaucion": None, "umbral_alerta_peligro": None},
    {"nombre": "ALTITUDE_T", "unidad": "m", "rango_minimo": -500, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9000},
    {"nombre": "HDOP_T", "unidad": "", "rango_minimo": 0, "rango_maximo": 50, "umbral_alerta_precaucion": 40, "umbral_alerta_peligro": 45},
    {"nombre": "LEVEL_T", "unidad": "%", "rango_minimo": 0, "rango_maximo": 100, "umbral_alerta_precaucion": 80, "umbral_alerta_peligro": 90},
    {"nombre": "UV_T", "unidad": "index", "rango_minimo": 0, "rango_maximo": 15, "umbral_alerta_precaucion": 12, "umbral_alerta_peligro": 15},
    {"nombre": "PM1_T", "unidad": "µg/m³", "rango_minimo": 0, "rango_maximo": 500, "umbral_alerta_precaucion": 150, "umbral_alerta_peligro": 300},
    {"nombre": "PM2_5_T", "unidad": "µg/m³", "rango_minimo": 0, "rango_maximo": 500, "umbral_alerta_precaucion": 150, "umbral_alerta_peligro": 300},
    {"nombre": "PM10_T", "unidad": "µg/m³", "rango_minimo": 0, "rango_maximo": 500, "umbral_alerta_precaucion": 150, "umbral_alerta_peligro": 300},
    {"nombre": "POWER_T", "unidad": "W", "rango_minimo": 0, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9000},
    {"nombre": "POWER2_T", "unidad": "W", "rango_minimo": 0, "rango_maximo": 10000, "umbral_alerta_precaucion": 8000, "umbral_alerta_peligro": 9000},
    {"nombre": "ENERGY_T", "unidad": "kWh", "rango_minimo": 0, "rango_maximo": 100000, "umbral_alerta_precaucion": 80000, "umbral_alerta_peligro": 90000},
    {"nombre": "ENERGY2_T", "unidad": "kWh", "rango_minimo": 0, "rango_maximo": 100000, "umbral_alerta_precaucion": 80000, "umbral_alerta_peligro": 90000},
    {"nombre": "WEIGHT_T", "unidad": "kg", "rango_minimo": 0, "rango_maximo": 1000, "umbral_alerta_precaucion": 800, "umbral_alerta_peligro": 950},
    {"nombre": "WEIGHT2_T", "unidad": "kg", "rango_minimo": 0, "rango_maximo": 1000, "umbral_alerta_precaucion": 800, "umbral_alerta_peligro": 950},
    {"nombre": "DESCONOCIDO", "unidad": "Indeterminado", "rango_minimo": None, "umbral_alerta_precaucion": None, "umbral_alerta_peligro": None, "rango_maximo": None }
]