"""Nodo: type -> TipoDato agregado

Revision ID: 02672b265995
Revises: 6ab833ac383d
Create Date: 2024-09-27 11:07:03.078108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02672b265995'
down_revision: Union[str, None] = '6ab833ac383d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodos', 'type',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('STATUS_T', 'TEMP_T', 'TEMP2_T', 'HUMIDITY_T', 'PRESSURE_T', 'LIGHT_T', 'SOIL_T', 'SOIL2_T', 'SOILR_T', 'SOILR2_T', 'OXYGEN_T', 'CO2_T', 'WINDSPD_T', 'WINDHDG_T', 'RAINFALL_T', 'MOTION_T', 'VOLTAGE_T', 'VOLTAGE2_T', 'CURRENT_T', 'CURRENT2_T', 'IT_T', 'LATITUDE_T', 'LONGITUDE_T', 'ALTITUDE_T', 'HDOP_T', 'LEVEL_T', 'UV_T', 'PM1_T', 'PM2_5_T', 'PM10_T', 'POWER_T', 'POWER2_T', 'ENERGY_T', 'ENERGY2_T', 'WEIGHT_T', 'WEIGHT2_T', name='tipodato'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodos', 'type',
               existing_type=sa.Enum('STATUS_T', 'TEMP_T', 'TEMP2_T', 'HUMIDITY_T', 'PRESSURE_T', 'LIGHT_T', 'SOIL_T', 'SOIL2_T', 'SOILR_T', 'SOILR2_T', 'OXYGEN_T', 'CO2_T', 'WINDSPD_T', 'WINDHDG_T', 'RAINFALL_T', 'MOTION_T', 'VOLTAGE_T', 'VOLTAGE2_T', 'CURRENT_T', 'CURRENT2_T', 'IT_T', 'LATITUDE_T', 'LONGITUDE_T', 'ALTITUDE_T', 'HDOP_T', 'LEVEL_T', 'UV_T', 'PM1_T', 'PM2_5_T', 'PM10_T', 'POWER_T', 'POWER2_T', 'ENERGY_T', 'ENERGY2_T', 'WEIGHT_T', 'WEIGHT2_T', name='tipodato'),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
